from django.urls import path
from c_admin import views

urlpatterns = [
    path('adminc', views.adminc, name='adminc'),
    path('students', views.students, name='students'),
    path('delete_fac/<int:id>', views.delete_fac, name='delete_fac'),
    path('delete_fac_allo/<int:id5>', views.delete_fac_allo, name='delete_fac_allo'),
    path('delete_std/<int:idd>', views.delete_std, name='delete_std'),
    path('delete_que/<int:id6>', views.delete_que, name='delete_que'),
    path('add_fac', views.add_fac, name='add_fac'),
    path('add_std', views.add_std, name='add_std'),
    path('add_que', views.add_que, name='add_que'),
    path('add_csv', views.add_csv, name='add_csv'),
    path('csv_up', views.csv_up, name='csv_up'),
    path('sem_ajax', views.sem_ajax, name='sem_ajex'),
    path('div_ajax', views.div_ajax, name='div_ajax'),
    path('sub_ajax', views.sub_ajax, name='sub_ajax'),
    path('fac_ajax_srch', views.fac_ajax_srch, name='fac_ajax_srch'),
    path('stream_ajax_srch', views.stream_ajax_srch, name='stream_ajax_srch'),
    path('sem_ajax_srch', views.sem_ajax_srch, name='sem_ajax_srch'),
    path('div_ajax_srch', views.div_ajax_srch, name='div_ajax_srch'),
    path('post_ajax_srch', views.post_ajax_srch, name='post_ajax_srch'),
    path('sub_ajax_srch', views.sub_ajax_srch, name='sub_ajax_srch'),
    path('fac_pro/<int:id3>', views.fac_pro, name='fac_pro'),
    path('std_pro/<int:id4>', views.std_pro, name='std_pro'),
    path('update_std', views.update_std, name='update_std'),
    path('update_fac', views.update_fac, name='update_fac'),
    path('que_update', views.que_update, name='que_update'),
    path('admin_login', views.admin_login, name='admin_login'),
    path('fac_allo', views.fac_allo, name='fac_allo'),
    path('pro_fac_allo', views.pro_fac_allo, name='pro_fac_allo'),
    path('logout', views.logout, name='logout'),
    path('admin_feedback', views.admin_feedback, name='admin_feedback'),
]