# Generated by Django 2.2.6 on 2019-10-22 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('roll', models.IntegerField(blank=True, null=True)),
                ('enroll', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(default='None', upload_to='pics/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='pics')),
                ('csv_tag', models.CharField(max_length=50)),
                ('csv_flag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Div',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fac_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Div')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_id', models.IntegerField()),
                ('que', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.IntegerField()),
                ('sub_name', models.CharField(max_length=100)),
                ('sem_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Sem')),
                ('stream_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Stream')),
            ],
        ),
        migrations.CreateModel(
            name='Std_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Div')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Sem')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Stream')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sem',
            name='stream_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Stream'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('msg', models.TextField()),
                ('q1', models.IntegerField()),
                ('q2', models.IntegerField()),
                ('q3', models.IntegerField()),
                ('q4', models.IntegerField()),
                ('q5', models.IntegerField()),
                ('q6', models.IntegerField()),
                ('q7', models.IntegerField()),
                ('q8', models.IntegerField()),
                ('q9', models.IntegerField()),
                ('q10', models.IntegerField()),
                ('q11', models.IntegerField()),
                ('q12', models.IntegerField()),
                ('q13', models.IntegerField()),
                ('fac_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Fac_Master')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Post')),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fac_master',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Post'),
        ),
        migrations.AddField(
            model_name='fac_master',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Sem'),
        ),
        migrations.AddField(
            model_name='fac_master',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Stream'),
        ),
        migrations.AddField(
            model_name='fac_master',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Subject'),
        ),
        migrations.AddField(
            model_name='fac_master',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='div',
            name='sem_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Sem'),
        ),
        migrations.AddField(
            model_name='div',
            name='stream_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Stream'),
        ),
    ]
