# Generated by Django 2.2.3 on 2019-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='que_id',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
