# Generated by Django 2.2.3 on 2019-09-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190921_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csv_id',
            field=models.CharField(max_length=50),
        ),
    ]
