# Generated by Django 2.2.3 on 2019-09-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190921_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csv',
            old_name='csv_id',
            new_name='csv_tag',
        ),
    ]
