# Generated by Django 2.2.3 on 2019-09-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190921_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csv_tag',
            field=models.FileField(upload_to='pics'),
        ),
    ]
