# Generated by Django 2.2.3 on 2019-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190921_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csv',
            field=models.FileField(upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='csv',
            name='csv_tag',
            field=models.CharField(max_length=50),
        ),
    ]
