# Generated by Django 2.2.3 on 2019-09-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190927_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fac_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Fac_Master'),
        ),
    ]
