# Generated by Django 2.2.3 on 2019-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190928_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='fac_master',
            name='img',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
