# Generated by Django 2.2.3 on 2019-10-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_fac_master_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fac_master',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
