# Generated by Django 2.2.3 on 2019-10-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20191003_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fac_master',
            name='img',
        ),
    ]
