# Generated by Django 2.2.3 on 2019-10-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_fac_master_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Post'),
            preserve_default=False,
        ),
    ]
