# Generated by Django 2.2.3 on 2019-10-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_feedback_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='csv_flag',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
