# Generated by Django 2.2.3 on 2019-10-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_csv_csv_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
