# Generated by Django 2.2.6 on 2019-10-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_feedback_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv',
            name='csv_tag',
        ),
    ]
