# Generated by Django 2.2.6 on 2019-10-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_csv_csv_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='csv_tag',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
